### ISSUE TITLE
Rozbicie na zakresy cenowe

### ISSUE THREAD

**Issue by oliwex** [gtworek/PrezentDlaInformatyka#2]
Prosba.
Dodac tego wiecej i zrobic zakresy cenowe np.
Do 100zl - taki prezent symboliczny
Do 500zl - po prostu prezent
Do 1000zl - prezent jak jestes "grubym kotletem"
Do 5000zl - costam

**Comment by gtworek** [comment]
Ma to sens. Właśnie dlatego użyłem GitHuba, żeby każdy mógł to zrobić.
